version: "3"
services:
  text-generation-webui-agentooba:
    image: text-generation-webui-agentooba:latest # you must build this yourself first
    container_name: text-generation-webui-agentooba
    environment:
      - EXTRA_LAUNCH_ARGS="--listen --verbose --extensions AgentOoba"
    ports:
      - 7860:7860  # Default web port
#      - 5000:5000  # Default API port
#      - 5005:5005  # Default streaming port
#      - 5001:5001  # Default OpenAI API extension port
    volumes:
      - ./data/characters:/app/characters
      - ./data/loras:/app/loras
      - ./data/models:/app/models
      - ./data/presets:/app/presets
      - ./data/prompts:/app/prompts
      - ./data/training:/app/training
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [gpu]
